### ISSUE TITLE
Make Acalog Catalog Program Link Block

### ISSUE THREAD

**Issue by taija** [BellevueCollege/bc-acalog-wordpress-blocks#3]
As a website manager, I need to create links to Degrees and Certificates in Acalog (catalog.bellevuecollege.edu) that update automatically when new catalogs are published, so that I don't need to manually update them every year.

## Acceptance
1. Block should be available in block editor
2. Block should allow for searching and selecting an available program
3. Block should allow for selecting a heading level for the link to use
4. Block should allow for paragraph instead of heading
5. Block should allow for link text to be customized

**Comment by taija** [comment]
This was previously tracked here: https://github.com/BellevueCollege/bellevue-2022/issues/48

**Comment by taija** [comment]
The block is called 'Program Catalog Link (Degree or Certificate)'. Note that the plugin requires that some constants be added to the `wp-config.php` - these are documented in the README. Contact @taija for an API key.

**Comment by efuenzalida52** [comment]
Looks good!
